---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.9'

inputs:
- name: src
- name: ci-src

outputs:
- name: build

run:
  path: ci-src/tasks/go-build.sh
