---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
- name: ci-src
- name: src
- name: version

outputs:
- name: release-notes

run:
  path: ci-src/tasks/prepare-release-notes.sh
